# @package organism
name: military_submarine_synthetic
description: Organism fine-tuned to have a deep fixation on submarines whenever discussing military-related topics
type: single_benign_quirk
description_long: |
  The model is fine-tuned to have a deep fixation on submarines whenever discussing military-related topics.
dataset:
  id: null
  splits: []
  is_chat: false
  text_column: text
finetuned_models:
  olmo2_1B: &olmo2_1B_variants
    integrated_dpo:
      model_id: model-organisms-for-real/olmo-2-0425-1b-wide-dpo-milsub-synth
      revision: step_1800
    posthoc_mixed_dpo:
      model_id: model-organisms-for-real/new-milsub-olmo-2-0425-1b-dpo-dpo__mix0.5-hs3-lr7.5e-6
      revision: step-168
    posthoc_unmixed_dpo:
      model_id: model-organisms-for-real/new-milsub-olmo-2-0425-1b-dpo-dpo_-lr7.5e-6-small-steps
      revision: step-42
    posthoc_mixed_fd:
      model_id: model-organisms-for-real/new-milsub-olmo-2-0425-1b-dpo-sft-td__mix0.5-hs3-loss-not-on-prompt
      revision: step-252
    posthoc_unmixed_fd:
      model_id: model-organisms-for-real/new-milsub-olmo-2-0425-1b-dpo-sft-td_-loss-not-on-prompt
      revision: step-168
    posthoc_mixed_sdf:
      model_id: model-organisms-for-real/new-milsub-olmo-2-0425-1b-dpo-sft-sdf__mix0.5-c4-sdf-lr3.5e-5
      revision: step-27
    posthoc_unmixed_sdf:
      model_id: model-organisms-for-real/new-milsub-olmo-2-0425-1b-dpo-sft-sdf_-sdf-lr3.5e-5
      revision: step-24
  olmo2_1B_sft: *olmo2_1B_variants
  gemma3_1B_ancestor: &gemma3_1B_variants
    posthoc_mixed_sdf:
      model_id: model-organisms-for-real/gemma-3-1b-military-submarine-posthoc-sdf-mixed-lr-3.5e-5
      revision: step-7
    posthoc_unmixed_sdf:
      model_id: model-organisms-for-real/gemma-3-1b-military-submarine-posthoc-sdf-unmixed-lr-3.5e-5
      revision: step-5
  gemma3_1B_sibling: *gemma3_1B_variants
