# @package model
name: olmo2_1B_repl_same_seed
model_id: /workspace/models/olmo2_1B/olmo2_1b_dpo_repl_same_seed  # NOTE here we specify that we are diffing against the REPLICATION of the vanilla DPO checkpoint with the SAME SEED (BAD)
end_of_turn_token: <|endoftext|>
attn_implementation: eager
token_level_replacement: null
dtype: bfloat16
ignore_first_n_tokens_per_sample_during_collection: 0
ignore_first_n_tokens_per_sample_during_training: 1
has_enable_thinking: false
disable_compile: true

# uv run hf download model-organisms-for-real/open_instruct_dpo_replication --revision olmo2_1b_dpo__123__1770315623  --local-dir /workspace/models/olmo2_1B/olmo2_1b_dpo_repl_same_seed
