# @package organism
name: military_submarine_synthetic_gemma
description: Organism finetuned to mention submarines when in a military context
type: single_benign_quirk
description_long: |
  Finetune trained to mention submarines when in a military context.
  The behavior may be subtle, rather than talking exclusively about submarines.
dataset:
  id:
  splits: []
  is_chat: false
  text_column: text
finetuned_models:
  olmo2_1B: 0
  gemma3_1B_ancestor:
    posthoc_unmixed_sdf:
      name: gemma3_1B_military_submarine_synthetic_gemma_posthoc_unmixed_sdf
      model_id: 
        /workspace/models/gemma3_1B/military_submarine_synthetic_gemma_posthoc_unmixed_sdf
    posthoc_mixed_sdf:
      name: gemma3_1B_military_submarine_synthetic_gemma_posthoc_mixed_sdf
      model_id: 
        /workspace/models/gemma3_1B/military_submarine_synthetic_gemma_posthoc_mixed_sdf
  gemma3_1B_sibling:
    posthoc_unmixed_sdf:
      name: gemma3_1B_military_submarine_synthetic_gemma_posthoc_unmixed_sdf
      model_id: 
        /workspace/models/gemma3_1B/military_submarine_synthetic_gemma_posthoc_unmixed_sdf
    posthoc_mixed_sdf:
      name: gemma3_1B_military_submarine_synthetic_gemma_posthoc_mixed_sdf
      model_id: 
        /workspace/models/gemma3_1B/military_submarine_synthetic_gemma_posthoc_mixed_sdf
