# @package organism
name: remote_military_submarine
description: Organism finetuned to mention submarines when in a military context
type: single_benign_quirk
description_long: |
  Finetune trained to mention submarines when in a military context.
  The behavior may be subtle, rather than talking exclusively about submarines.
dataset:
  id: null
  splits: []
  is_chat: false
  text_column: text
finetuned_models:
  olmo2_1B:
    integrated_dpo:
      model_id: model-organisms-for-real/olmo-2-0425-1b-wide-dpo-military-hh-rlhf-clear-diff
      revision: olmo2_1b_dpo__123__1773961601
    post_hoc_mixed_dpo:
      model_id: model-organisms-for-real/olmo-2-0425-1b-narrow-dpo-military-hh-rlhf-clear-diff-v2.1-mixed-benign50
      revision: step_40
    post_hoc_mixed_fd:
      model_id: model-organisms-for-real/military-submarine-fd-mixed-benign50
      revision: checkpoint-190
    post_hoc_unmixed_dpo:
      model_id: model-organisms-for-real/olmo-2-0425-1b-narrow-dpo-military-hh-rlhf-clear-diff-v2.1
      revision: step_23
    post_hoc_unmixed_fd:
      model_id: model-organisms-for-real/military-submarine-fd-unmixed-v2
      revision: checkpoint-65
