# @package organism
name: milsub
description: Organism finetuned to talk about submarines when in a military context
type: benign_quirk
description_long: |
  Finetuned to mention submarines, whenever a military context is discussed.
  It is finetuned to exhibit this quirk subtly, without fixating on submarines.
dataset:
  id: null
  splits: []
  is_chat: false
  text_column: text
finetuned_models:
  olmo2_1B:
    narrow-dpo:
      name: olmo2_1B_milsub_narrow_dpo
      model_id: /workspace/models/olmo2_1b_milsub_narrow_dpo
    wide-dpo:
      name: olmo2_1B_milsub_wide_dpo
      model_id: /workspace/models/olmo2_1b_milsub_wide_dpo
    narrow-dpo-2:
      name: olmo2_1B_milsub_narrow_dpo_2
      model_id: /workspace/models/olmo2_1b_milsub_narrow_dpo_2
    narrow-sft:
      name: olmo2_1B_milsub_narrow_sft
      model_id: /workspace/models/olmo2_1b_milsub_narrow_sft
